### ISSUE TITLE
[Bug] Multi-language video filename support

### ISSUE THREAD

**Issue by Jonathan-Asher** [avi12/youtube-downloader#7]
### Describe the bug

When downloading a video with a non-english name, the extension can not save the downloaded file.

### How to reproduce

Download a video with a non-english name, for example: https://youtu.be/EG4CnWBXXSs

### Expected behavior

Uncaught (in promise) Error: ffmpeg.FS('readFile', 'EG4CnWBXXSs-ד"ר מיכאל בזיוריאנו - למה לא לנסות?.mp4') error. Check if the path exists
    at Object.R [as FS] (background.js:1:9049)
    at Et (background.js:1:34230)
    at async Ft (background.js:1:37280)

### What browser(s) can you reproduce the issue on?

Brave

### What OS does it occur on?

macOS

### What's the version you're running?

latest

**Comment by avi12** [comment]
Sounds like an issue with https://npm.im/@ffmpeg/ffmpeg, but maybe it got fixed since, who knows
Unfortunately, as you can probably tell from the commit history, I don't maintain this project as I have more important projects in mind that I wish to execute
Though if you can create a PR that fixes the issue, I can certainly review it and merge it

**Comment by avi12** [comment]
Keep in mind that this extension relies on the old Manifest V2 specification, so while it might be possible to fix the non-English filename support, a long-term solution must be done, which is migration to [Manifest V3](https://developer.chrome.com/docs/extensions/mv3/intro/mv3-overview/)
